import type { Metadata } from "next";
import { CartProvider } from "@/contexts/CartContext";
import { CustomerAuthProvider } from "@/contexts/CustomerAuthContext";
import { Header } from "@/components/layout/Header";
import "./globals.css";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ja">
      <body>
        <CartProvider>
          <CustomerAuthProvider>
            <Header />

            <main>{children}</main>
          </CustomerAuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
